#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

if [[ ${EUID:-$(id -u)} -eq 0 ]]; then
  echo "WARNING: configuration files will be owned by root. Prefer running this as the rAthena service user." >&2
fi

safe_value() {
  local label="$1" value="$2"
  if [[ ! "$value" =~ ^[A-Za-z0-9._~@%+=:-]+$ ]]; then
    echo "ERROR: $label contains unsupported characters for this helper." >&2
    echo "Use letters, digits and . _ ~ @ % + = : - only." >&2
    exit 1
  fi
}

read -r -p "MariaDB host [127.0.0.1]: " DB_HOST; DB_HOST=${DB_HOST:-127.0.0.1}
read -r -p "MariaDB port [3306]: " DB_PORT; DB_PORT=${DB_PORT:-3306}
read -r -p "Database name [ragnarok]: " DB_NAME; DB_NAME=${DB_NAME:-ragnarok}
read -r -p "Database user [ragnarok]: " DB_USER; DB_USER=${DB_USER:-ragnarok}
read -r -s -p "Database password: " DB_PASS; echo
read -r -p "Inter-server user [wyo_server]: " SERVER_USER; SERVER_USER=${SERVER_USER:-wyo_server}
read -r -s -p "Inter-server password: " SERVER_PASS; echo
read -r -p "Public server IP/DNS (leave empty for local testing): " PUBLIC_HOST
read -r -p "Server display name [World Yggdrasil Online]: " SERVER_NAME; SERVER_NAME=${SERVER_NAME:-World Yggdrasil Online}

safe_value "DB host" "$DB_HOST"
safe_value "DB port" "$DB_PORT"
safe_value "DB name" "$DB_NAME"
safe_value "DB user" "$DB_USER"
safe_value "DB password" "$DB_PASS"
safe_value "inter-server user" "$SERVER_USER"
safe_value "inter-server password" "$SERVER_PASS"
if [[ -n "$PUBLIC_HOST" ]]; then safe_value "public host" "$PUBLIC_HOST"; fi

mkdir -p conf/import tools/wyo-linux/generated
STAMP=$(date +%Y%m%d-%H%M%S)
for f in inter_conf.txt char_conf.txt map_conf.txt web_conf.txt; do
  if [[ -s "conf/import/$f" ]]; then cp -a "conf/import/$f" "conf/import/$f.bak.$STAMP"; fi
done

cat > conf/import/inter_conf.txt <<CFG
// Generated by tools/wyo-linux/configure-production.sh
login_server_ip: $DB_HOST
login_server_port: $DB_PORT
login_server_id: $DB_USER
login_server_pw: $DB_PASS
login_server_db: $DB_NAME
ipban_db_ip: $DB_HOST
ipban_db_port: $DB_PORT
ipban_db_id: $DB_USER
ipban_db_pw: $DB_PASS
ipban_db_db: $DB_NAME
char_server_ip: $DB_HOST
char_server_port: $DB_PORT
char_server_id: $DB_USER
char_server_pw: $DB_PASS
char_server_db: $DB_NAME
map_server_ip: $DB_HOST
map_server_port: $DB_PORT
map_server_id: $DB_USER
map_server_pw: $DB_PASS
map_server_db: $DB_NAME
web_server_ip: $DB_HOST
web_server_port: $DB_PORT
web_server_id: $DB_USER
web_server_pw: $DB_PASS
web_server_db: $DB_NAME
log_db_ip: $DB_HOST
log_db_port: $DB_PORT
log_db_id: $DB_USER
log_db_pw: $DB_PASS
log_db_db: $DB_NAME
CFG

cat > conf/import/char_conf.txt <<CFG
// Generated by tools/wyo-linux/configure-production.sh
userid: $SERVER_USER
passwd: $SERVER_PASS
server_name: $SERVER_NAME
CFG
cat > conf/import/map_conf.txt <<CFG
// Generated by tools/wyo-linux/configure-production.sh
userid: $SERVER_USER
passwd: $SERVER_PASS
CFG

if [[ -n "$PUBLIC_HOST" ]]; then
  cat >> conf/import/char_conf.txt <<CFG
char_ip: $PUBLIC_HOST
CFG
  cat >> conf/import/map_conf.txt <<CFG
map_ip: $PUBLIC_HOST
CFG
fi

cat > conf/import/web_conf.txt <<CFG
// Keep rAthena web API private by default. Put a reverse proxy in front if needed.
bind_ip: 127.0.0.1
web_port: 8888
CFG

chmod 600 conf/import/inter_conf.txt conf/import/char_conf.txt conf/import/map_conf.txt conf/import/web_conf.txt

# SQL snippet to replace the insecure upstream s1/p1 inter-server account.
# Values were restricted above to a conservative character set.
cat > tools/wyo-linux/generated/wyo-server-account.sql <<SQL
UPDATE login
SET userid='${SERVER_USER}', user_pass='${SERVER_PASS}', sex='S'
WHERE account_id=1;
SQL
chmod 600 tools/wyo-linux/generated/wyo-server-account.sql

cat <<MSG

Configuration written.
IMPORTANT:
  1. Import sql-files/main.sql, logs.sql and web.sql into your database as needed.
  2. Import WYO custom schemas documented in doc/WYO/WYO_LINUX_INSTALL.md.
  3. After main.sql, execute:
       tools/wyo-linux/generated/wyo-server-account.sql
  4. Do NOT commit conf/import/*_conf.txt or tools/wyo-linux/generated/.
MSG
